services:
  db:
    image: mysql:8.0
    container_name: e-love-chat-service-db
    env_file:
      - ./docker/db-app/db.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 10s
      timeout: 5s
      retries: 5

  e-love-chat-service-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    container_name: chat-service-api
    ports:
      - "8081:8001"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./api
        target: /app/api
      - type: bind
        source: ./auth
        target: /app/auth
      - type: bind
        source: ./configuration
        target: /app/configuration
      - type: bind
        source: ./core
        target: /app/core
      - type: bind
        source: ./alembic
        target: /app/alembic
      - type: bind
        source: ./alembic.ini
        target: /app/alembic.ini
      - type: bind
        source: ./docker
        target: /app/docker
      - type: bind
        source: ./main.py
        target: /app/main.py
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
    driver: local
